import { 
  GlassWater, 
  Utensils, 
  Footprints, 
  Flame, 
  ChevronLeft, 
  ChevronRight,
  Plus,
  Minus,
  Trash2,
  History,
  Home,
  LogOut,
  User,
  Activity,
  TrendingUp,
  Search,
  Sparkles,
  Sun,
  Moon,
  Bike,
  Dumbbell,
  Timer
} from "lucide-react";

export const Icons = {
  Water: GlassWater,
  Food: Utensils,
  Steps: Footprints,
  Burn: Flame,
  Left: ChevronLeft,
  Right: ChevronRight,
  Plus: Plus,
  Minus: Minus,
  Delete: Trash2,
  History: History,
  Home: Home,
  Logout: LogOut,
  User: User,
  Activity: Activity,
  Trend: TrendingUp,
  Search: Search,
  Sparkles: Sparkles,
  Sun: Sun,
  Moon: Moon,
  Bike: Bike,
  Gym: Dumbbell,
  Timer: Timer
};